version: "3"
services:
   odoo:
      build:
         context: .
      container_name: ${PROJECT_NAME}
      command: odoo -u openeducat_student_inscription --dev=all
      depends_on:
         - db
      ports:
         - ${ODOO_PORT}:8069
      volumes:
         - web:/var/lib/odoo
         - ./config:/etc/odoo
         - ./enterprise:/mnt/extra-addons
         - ./custom:/mnt/custom-addons
         - ./internal:/mnt/internal-addons
         - ./third_party:/mnt/external-addons
      environment:
         - PYTHONUNBUFFERED=0
      # restart: always
      networks:
         - postgres_bd
   db:
      container_name: ${PROJECT_NAME}_db
      image: postgres:${POSTGRES_VERSION}
      environment:
         - POSTGRES_DB=postgres
         - POSTGRES_PASSWORD=odoo
         - POSTGRES_USER=odoo
         - PGDATA=/var/lib/postgresql/data/pgdata
      volumes:
         - db:/var/lib/postgresql/data/pgdata
      # restart: always
      networks:
         - postgres_bd
   pgadmin:
      container_name: ${PROJECT_NAME}_pgadmin
      image: dpage/pgadmin4
      environment:
         PGADMIN_DEFAULT_EMAIL: jdap.dmc@gmail.com
         PGADMIN_DEFAULT_PASSWORD: odoo
         PGADMIN_CONFIG_SERVER_MODE: "False"
      networks:
         - postgres_bd
      volumes:
         - pgadmin:/root/.pgadmin

      ports:
         - ${PGADMIN_PORT}:80
      # restart: unless-stopped

networks:
   postgres_bd:

volumes:
   web:
   db:
   pgadmin:
