{
    "name": "Note Charge",
    "version": "14.0.0.0.0",
    "author": "MITIS",
    "contributors": [],
    "maintainer": "MITIS",
    "website": "",
    "images": [],
    "category": "OpenEducat",
    "license": "LGPL-3",
    "summary": "",
    "depends": ["base", "openeducat_core"],
    "data": [
        "security/ir.model.access.csv",
        "views/note_charge_views.xml",
        "views/faculty_view.xml",
        "views/student_view.xml",
        "wizards/wizard_charge_note_views.xml",
    ],
    "assets": {},
    "external_dependencies": {},
    "demo": [],
    "css": [],
    "qweb": [],
    "installable": True,
    "auto_install": False,
    "application": True,
}
