{
    'name': 'Partner Diverse Gender',
    'version': '14.0',
    'author': 'Franyer Hidalgo <fhidalgo.dev@gmail.com>',
    'contributors': ['Franyer Hidalgo <fhidalgo.dev@gmail.com>'],
    'website': 'https://gitlab.com/fhidalgo.dev',
    'images': [],
    'category': 'contacts',
    'license': 'LGPL-3',
    'summary': 'Diverse Gender',
    'description': """Diverse Gender""",
    'depends': ['base',
                'contacts',
                ],
    'data': ['security/ir.model.access.csv',
             'data/partner.diverse.gender.csv',
             'views/partner_diverse_gender_view.xml',
             'views/partner_view.xml',
             ],
    'demo': [],
    'css': [],
    'qweb': [],
    'installable': True,
    'auto_install': False,
    'application': False
}
