{
    'name': 'UNEXCA OpenEducat',
    'version': '14.0',
    'author': 'MITIS-UNEXCA',
    'contributors': [''],
    'website': '',
    'images': [],
    'category': 'OpenEducat',
    'license': 'LGPL-3',
    'summary': 'Characteristics of unexca',
    'description': """Characteristics of unexca""",
    'depends': ['base',
                'openeducat_core',
                'openeducat_admission',
                ],
    'data': [
        'data/res_company.xml',
        'data/product.xml',
        'data/course.xml',
        'data/academic_year.xml',
        'data/admission.xml',
    ],
    'demo': [],
    'css': [],
    'qweb': [],
    'installable': True,
    'auto_install': False,
    'application': False
}
